apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv
  target:
    name: n8n-env
    creationPolicy: Owner
  data:
    - secretKey: N8N_BASIC_AUTH_PASSWORD
      remoteRef:
        # Path is relative to ClusterSecretStore provider.path (kv)
        key: apps/n8n/app
        property: N8N_BASIC_AUTH_PASSWORD
