image:
  repository: bitnami/n8n
  tag: 1.71.3-debian-12-r0

service:
  type: ClusterIP

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - name: N8N_BASIC_AUTH_USER
    value: "admin"
  - name: N8N_BASIC_AUTH_PASSWORD
    value: "CHANGEME"
  - name: GENERIC_TIMEZONE
    value: "UTC"
  - name: EXECUTIONS_PROCESS
    value: "own"
  - name: N8N_METRICS
    value: "true"
