apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-kv
spec:
  provider:
    vault:
      # Vault service inside the cluster (adjust namespace if changed)
      server: http://vault.infra.svc.cluster.local:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          # Mount path for Vault's Kubernetes auth method
          mountPath: kubernetes
          # Role configured by tools/scripts/vault_k8s_onboard.sh
          role: eso
          # Use ESO controller's ServiceAccount for TokenRequest
          serviceAccountRef:
            name: external-secrets
            namespace: infra
