auth:
  username: user
  password: CHANGEME
  erlangCookie: CHANGEMECOOKIE

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  size: 1Gi

metrics:
  enabled: true
