deploymentMode: SingleBinary

loki:
  storage:
    type: filesystem
  useTestSchema: true

singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 5Gi

# Disable caches and SSD components for SingleBinary + filesystem
chunksCache:
  enabled: false
resultsCache:
  enabled: false
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
