mode: deployment
image:
  repository: otel/opentelemetry-collector-contrib
command:
  name: otelcol-contrib
config:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4318
        grpc:
          endpoint: 0.0.0.0:4317
  exporters:
    otlp:
      endpoint: tempo.observability.svc.cluster.local:4317
      tls:
        insecure: true
  processors:
    batch: {}
  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp]
