tempo:
  storage:
    trace:
      backend: local
      wal:
        path: /var/tempo/wal
      local:
        path: /var/tempo/traces
  server:
    http_listen_port: 3200
  persistence:
    enabled: true
    size: 5Gi

